### ISSUE TITLE
Recommend using two separate buttons

### ISSUE THREAD

**Issue by swehba** [OfficerHalf/obsidian-collapse-all#12]
I really appreciate your adding the expand all functionality, but wouldn't it make more sense to have it as a separate button? As it is, to expand all, you must first collapse all if anything is expanded. Seems more intuitive to just have two buttons.

**Comment by OfficerHalf** [comment]
Personal preference I suppose. I'll consider about adding a toggle to enable two buttons vs one.

**Comment by OfficerHalf** [comment]
For now, if you'd like, you can use the commands in the command palette to expand/collapse at will.

**Comment by OfficerHalf** [comment]
Planning this as an option for 1.4.0.

**Comment by OfficerHalf** [comment]
Added in #23
