### ISSUE TITLE
"styles.css not found" error on update

### ISSUE THREAD

**Issue by kzhovn** [OfficerHalf/obsidian-collapse-all#13]
On updating, I got 
`app.js:1 GET https://github.com/OfficerHalf/obsidian-collapse-all/releases/download/1.2.0/styles.css 404` and then `Collapse All: styles.css not found`.

**Comment by OfficerHalf** [comment]
Huh interesting. It isn't breaking things though right?

**Comment by kzhovn** [comment]
Nope, everything seems to be working as expected, though if there was some weirdness in how it looked I wouldn't necessarily expect to notice, I don't pay a lot of attention to that.

**Comment by OfficerHalf** [comment]
I'm not able to reproduce this. It seems like obsidian is looking for a styles.css file and not finding it even though I don't provide one and never have. Not sure why.

**Comment by kzhovn** [comment]
I can reproduce it if I uninstall the plugin and then reinstall, it doesn't happen on load.

**Comment by OfficerHalf** [comment]
Okay, I reproduced it like that. However, this is definitely a bug with obsidian, not my plugin. This happens with any plugin that provides no css; I was able to reproduce the same thing with https://github.com/denolehov/obsidian-git
