### ISSUE TITLE
Possibly inconsistent Obsidian version dependencies

### ISSUE THREAD

**Issue by claremacrae** [OfficerHalf/obsidian-collapse-all#15]
I'm not sure if this matters or not but....

```bash
find . -type f | xargs grep 0.12.
./versions.json:  "1.2.0": "0.12.10",
./package.json:    "obsidian": "^0.12.11",
./manifest.json:  "minAppVersion": "0.12.10",
```

Is it intentional that there are two references to Obsidian "0.12.10" and one to "^0.12.11" ?

**Comment by OfficerHalf** [comment]
Definitely not intentional. I don't think there's much difference wrt this plugin between those, but I'll get them all lined up. Good catch!

**Comment by OfficerHalf** [comment]
Fixed in `versions.json` in #17, still need to update in `manifest.json`
