### ISSUE TITLE
Provide "visibility cycling"

### ISSUE THREAD

**Issue by ngirard** [OfficerHalf/obsidian-collapse-all#24]
Heya,

one feature I've always appreciated in [Org mode](https://orgmode.org) is the so-called [visibility cycling](https://orgmode.org/manual/Global-and-local-cycling.html). That is, by repeteadly hitting just one shortcut, the view switches between these 3 different states:
```
,-> FOLDED -> CHILDREN -> SUBTREE --.
'-----------------------------------'
```
- in the *folded* state, everything is folded;
- in the *children* state, the contents is made visible but the sub-headers (children) are kept folded;
- in the *subtree* state, everything is expanded and made visible.

There's also a distinction between "global cycling", by which you alter the visibility of the whole file, and "local cycling", by which you alter the visibility of the part of the file where the cursor is located.

Here's one gif I could find to illustrate how it feels like:
<img src="https://christiantietze.de/posts/2019/06/org-fold-heading/20190629123107_fold-level-demo.gif"/>

and in the Obsidian forum is has been discussed [here](https://forum.obsidian.md/t/org-mode-style-header-cycling-folding-shortcuts/5947) and [here](https://forum.obsidian.md/t/fold-unfold-headings-up-to-specific-level-hotkeys/8276).

It would be great if your plugin could provide such functionality !

Cheers, and thanks for your work !

**Comment by OfficerHalf** [comment]
@ngirard I think this is probably out of scope of this plugin; this only deals with the folders in the file explorer and tag pane. It doesn't do anything to folded headings in the editor.
