### ISSUE TITLE
Collapse + Expand to certain level (1-4)

### ISSUE THREAD

**Issue by mochsner** [OfficerHalf/obsidian-collapse-all#27]
In JetBrains' IDE there's a nifty feature where you can collapse to a certain level (high level class is ctrl+shift+1, functions is ctrl+shift+2 for typical code) -- would that be possible to add features in for here to a certain level

So, instead of having ctrl + shift + 2 to expand all, it'd expand the folders in root, then ctrl+shift+3 expands the ones in those folders, etc.

![image](https://user-images.githubusercontent.com/19310711/157912129-764b958d-0480-4a0e-9160-2b5c3e6ecd1e.png)

**Comment by OfficerHalf** [comment]
@mochsner is this what you mean?

I have the following structure:

```
Folder 1
Folder 1/Folder 2
Folder 1/Folder 2/Folder 3
Folder 1/Folder 2/Folder 3/Folder 4
```

- Expand 1 level would expand only the folders in the root, but not children
- Expand 2 levels would expand Folder 1, Folder 2 and other folders of the same depth
- Expand 3 levels would expand Fodler 1, Folder 2, Folder 3, and other folders of the same depth
- etc

**Comment by OfficerHalf** [comment]
Closing this as the collapse / expand functionality is all within obsidian now, and it does not support this.
