### ISSUE TITLE
Feature request: Pick one folder and expand all subfolders under it

### ISSUE THREAD

**Issue by andrewheekin** [OfficerHalf/obsidian-collapse-all#28]
Instead of expanding all folders, it'd be nice to pick a single folder and expand all subfolders that belong to it. Since many users group top level Obsidian folders by over-arching category, expanding all folders in that particular category would be useful.

For example, if I have a top level folder named "Javascript Learning" and am reading about the JS event loop, then I'd go and expand all folders within the "Javascript Learning" folder to give me a kind of "workspace" to categorize incoming knowledge on how the event loop pulls in stack frames from the call stack, etc

**Comment by OfficerHalf** [comment]
This is a great idea, and shouldn't be difficult.

**Comment by OfficerHalf** [comment]
Closed in #29

**Comment by OfficerHalf** [comment]
ACTUALLY closed in v1.5.1. 😁
