### ISSUE TITLE
how to collapse folder using js?

### ISSUE THREAD

**Issue by hyaray** [OfficerHalf/obsidian-collapse-all#31]
`document.querySelectorAll(".nav-folder-children > .nav-folder")[0]` is the first folder, how to collapse it?
thanks a lot. so I can done this using QuickAdd, needn't to install too much plugins

**Comment by OfficerHalf** [comment]
I'm not sure I understand. You want to collapse a folder but not with this plugin? I'm not sure if you can with a query selector - you need the internal folder instance. I don't know if QuickAdd gives you access to that.

Once you have a reference to the `TFolder`, you can just call `setCollapsed` https://github.com/OfficerHalf/obsidian-collapse-all/blob/main/src/provider/file-explorer.ts#L64

**Comment by hyaray** [comment]
>You want to collapse a folder but not with this plugin?
Yes, I only want to collapse all folders, so I don't want to install a plugin just for one feature.

> Once you have a reference to the TFolder, you can just call setCollapsed
`QuickAdd` should has access to deal it. Thanks a lot, I will have a try.
Best wishes!!

**Comment by OfficerHalf** [comment]
Well collapsing all folders is what this plugin does best. 🤣 But glad to be of service regardless.
