### ISSUE TITLE
This plugin is still useful!

### ISSUE THREAD

**Issue by CabbageCanFly** [OfficerHalf/obsidian-collapse-all#39]
The latest v1.0.0 Obsidian update added the collapse all button natively, but it doesn't have the command in the command palette like this plugin!

The note in the README about the plugin being "no longer needed" isn't totally true because of this :p

I still find the command palette shortcut to be pretty handy.

**Comment by beetrootpaul** [comment]
Same for me, I sadly realised I no longer can attach a shortcut to the now native command. Is there any place where I could report that need for the official Obsidian app?

**Comment by CabbageCanFly** [comment]
> Is there any place where I could report that need for the official Obsidian app?

@beetrootpaul I think new features are requested here: https://forum.obsidian.md/c/feature-requests/8  
I haven't requested it yet, so I guess you could go ahead and report it there.

**Comment by beetrootpaul** [comment]
@CabbageCanFly Thanks, here you go! 🙂 👉 https://forum.obsidian.md/t/add-hotkey-binding-for-explorers-collapse-all-action/45367

**Comment by Cr8zyIvan** [comment]
Same.
This Plugin is still useful. Obsidian has no native Hotkeys to Activate "Collapse All" or "Expand All" (as of 2023-08-02). Party On Wayne!

**Comment by OfficerHalf** [comment]
Thanks everyone. I'll work on an update to this plugin that allows it to work better with the internal collapse/expand to add a hot key, at least until the obsidian devs add one.

**Comment by OfficerHalf** [comment]
Done in #40, once released please update and check the plugin's settings. You'll probably need to rebind the hotkeys.
