### ISSUE TITLE
After the Android Obsidian is upgraded to 0.1.4, the plug-in cannot be enabled

### ISSUE THREAD

**Issue by tyf2018** [OfficerHalf/obsidian-collapse-all#8]
Very useful plugin，Thanks developer.
After the Android Obsidian is upgraded to 0.1.4, the plug-in cannot be enabled.

**Comment by OfficerHalf** [comment]
I don't have the app, so I can't debug it. I'm honestly shocked it worked at all.

If the same bug appears on the desktop app, I can fix it, but at least for now you might be out of luck unless someone else wants to take a look for me.

**Comment by OfficerHalf** [comment]
I don't have the app, so I can't debug it. I'm honestly shocked it worked at all.

If the same bug appears on the desktop app, I can fix it, but at least for now you might be out of luck unless someone else wants to take a look for me.

**Comment by tyf2018** [comment]
> I don't have the app, so I can't debug it. I'm honestly shocked it worked at all.
> 
> If the same bug appears on the desktop app, I can fix it, but at least for now you might be out of luck unless someone else wants to take a look for me.

Is it convenient for you to provide an email address? I send the app to you

**Comment by OfficerHalf** [comment]
Closing in favor of #9

**Comment by OfficerHalf** [comment]
@tyf2018 version 1.2.0 released with mobile enabled.
