### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by iamrecursion** [OfficerHalf/obsidian-collapse-all#9]
It would be great if you could unmark the plugin as `desktopOnly`. I've done it manually and there are absolutely no problems with it working on mobile in my experience.

**Comment by OfficerHalf** [comment]
Now that the mobile app is publicly available I can test this and release a new version. Should be available this week

**Comment by OfficerHalf** [comment]
@iamrecursion version 1.2.0 released with mobile enabled.

**Comment by iamrecursion** [comment]
Brilliant, thank you!!
